// End-to-end checks against the static build. Run: npm run build && npm start, then npm run test:e2e
import { chromium } from "playwright-core";
const BASE = process.env.BASE ?? "http://localhost:4173";
const b = await chromium.launch({ executablePath: process.env.CHROMIUM ?? "/usr/bin/chromium", args: ["--no-sandbox"] });
const pg = await b.newPage({ viewport: { width: 1280, height: 860 } });
const errs = [];
pg.on("pageerror", (e) => errs.push(String(e)));
pg.on("console", (m) => { if (m.type() === "error" && !/404/.test(m.text())) errs.push(m.text().slice(0, 200)); });
let failed = false;
const ok = (c, msg) => { if (!c) failed = true; console.log(c ? "PASS" : "FAIL", msg); };
await pg.goto(`${BASE}/`, { waitUntil: "networkidle" });
await pg.locator("header .btn", { hasText: "Замовити сайт" }).click();
await pg.waitForTimeout(400);
ok(await pg.locator("dialog[open]").count() === 1, "modal opens");
const D = pg.locator("dialog[open]");
await D.getByRole("button", { name: /Замовити через ONEKNIGHT/ }).click();
await D.getByRole("button", { name: "Створити акаунт" }).click();
ok(await pg.locator("[aria-invalid='true']").count() >= 3, "validation errors shown on empty register");
await D.getByLabel("Ім'я").fill("Тест");
await D.getByLabel("Телефон").fill("+380 67 000 00 00");
await D.getByLabel("Електронна пошта").fill("t@example.com");
await D.getByLabel("Пароль").fill("password123");
await D.getByRole("button", { name: "Створити акаунт" }).click();
await pg.waitForTimeout(300);
ok(await D.getByText("Що вам потрібно?").count() === 1, "service step after register");
ok(!(await pg.evaluate(() => localStorage.getItem("ok.demo-session") ?? "")).includes("password"), "password not stored");
await D.getByRole("button", { name: /^Сайт/ }).first().click();
await D.getByRole("button", { name: "Далі" }).click();
ok(await D.getByText("Опишіть коротко").count() === 1, "brief validation");
await D.getByLabel("Чим займається бізнес?").fill("Робимо сувеніри з дерева");
await D.getByRole("button", { name: "Далі" }).click();
await pg.waitForTimeout(300);
const tg = await D.getByRole("link", { name: "Відкрити Telegram" }).getAttribute("href");
ok(tg?.startsWith("https://t.me/poulpefounder?text=") && decodeURIComponent(tg).includes("сувеніри"), "telegram handoff link prefilled");
await pg.keyboard.press("Escape");
await pg.waitForTimeout(300);
ok(await pg.locator("header .btn", { hasText: "Відкрити ONEKNIGHT" }).count() === 1, "header CTA switches to Відкрити ONEKNIGHT");
// pricing -> brief with type preselected
await pg.evaluate(() => document.querySelector("#pricing").scrollIntoView());
await pg.getByRole("radio", { name: /Корпоративний сайт/ }).click();
await pg.getByRole("button", { name: /Розрахувати мій сайт/ }).click();
await pg.waitForTimeout(300);
ok((await pg.locator("dialog[open]").getByLabel("Який сайт потрібен?").inputValue()) === "corporate", "calculator preselects site type");
await pg.keyboard.press("Escape");
// funnel keyboard
await pg.evaluate(() => document.querySelector("#funnel").scrollIntoView());
await pg.getByRole("tab", { name: /Продаж/ }).click();
ok((await pg.locator("#funnel-panel").innerText()).includes("12"), "funnel stage selection");
// playground module install -> nav item
await pg.evaluate(() => document.querySelector("#modules").scrollIntoView());
await pg.waitForTimeout(1500);
await pg.locator(".ok-market .ok-module", { hasText: "Нова пошта" }).getByRole("button", { name: /Встановити/ }).click();
await pg.waitForTimeout(300);
ok(await pg.locator(".ok-market .ok-module", { hasText: "Нова пошта" }).getByText("Підключено").count() === 1, "marketplace install");
await pg.evaluate(() => document.querySelector("#playground").scrollIntoView());
await pg.waitForTimeout(800);
await pg.locator(".ok-side .ok-navbtn", { hasText: "Замовлення" }).click();
await pg.locator(".ok-row").first().click();
await pg.getByRole("button", { name: /Створити ТТН/ }).click();
ok(await pg.getByText(/DEMO-\d+/).count() === 1, "waybill after Nova Poshta module");
await pg.goto(`${BASE}/en/`, { waitUntil: "networkidle" });
ok((await pg.locator("h1").innerText()).includes("Your business deserves"), "english page");
const r = await pg.goto(`${BASE}/nope/`, { waitUntil: "networkidle" });
ok(r.status() === 404 && (await pg.locator("h1:visible").innerText()).includes("Ви заблукали"), "404 page");
await pg.goto(`${BASE}/en/nope/`, { waitUntil: "networkidle" });
ok((await pg.locator("h1:visible").innerText()).includes("You got lost"), "404 page english");
console.log("errors:", errs.length ? errs : "none");
if (errs.length || failed) process.exitCode = 1;
await b.close();
